"""
Situation model representing synthesized circumstances across multiple events and goals.
A Situation is NOT an agent; it is a generic data structure representing emerging context.
"""

from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
import json
from typing import Any, Dict, List, Optional
import uuid

from personal_intelligence.core.events.models import (
    ensure_timezone_aware,
    format_iso8601,
)


class SituationPriority(str, Enum):
    """Priority categorization for situations."""
    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    INFORMATIONAL = "informational"


class StandardSituationCategory(str, Enum):
    """
    Standard candidate situation categories generated by candidate generators.
    These are candidate patterns, not an exhaustive closed taxonomy.
    """
    GOAL_RISK = "goal_risk"
    UNRESOLVED_ACTION_ITEM_BEFORE_MILESTONE = "unresolved_action_item_before_milestone"
    CONFLICTING_COMMITMENTS = "conflicting_commitments"
    PROLONGED_INACTIVITY_ON_PRIORITY = "prolonged_inactivity_on_priority"
    UNUSUAL_CHANGE = "unusual_change"
    INFORMATION_GAP = "information_gap"
    EXTERNAL_DEPENDENCY_RISK = "external_dependency_risk"
    OPPORTUNITY = "opportunity"
    NOVEL_PATTERN = "novel_pattern"
    NOVEL_SITUATION = "novel_situation"

    # Compatibility aliases
    POSSIBLE_FORGOTTEN_COMMITMENT = "possible_forgotten_commitment"
    UPCOMING_PREPARATION_NEED = "upcoming_preparation_need"
    SCHEDULE_CONFLICT = "schedule_conflict"
    UNRESOLVED_ISSUE = "unresolved_issue"
    PROLONGED_ACTIVITY = "prolonged_activity"


class SituationStatus(str, Enum):
    """Lifecycle status of a situation."""
    OPEN = "open"
    MONITORING = "monitoring"
    RESOLVED = "resolved"
    CLOSED = "closed"
    EXPIRED = "expired"
    SUPPRESSED = "suppressed"

    # Aliases for backwards compatibility
    INVESTIGATING = "monitoring"



@dataclass
class Situation:
    """
    Generic representation of an assessed situation spanning arbitrary personal events.
    Serves as an integrated context frame for reasoning.
    """
    type: str
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    status: str = SituationStatus.OPEN.value
    priority: str = SituationPriority.MEDIUM.value
    novelty: float = 0.0
    context: Dict[str, Any] = field(default_factory=dict)
    evidence: List[Any] = field(default_factory=list)
    related_goals: List[str] = field(default_factory=list)
    information_required: bool = False
    investigation_target: Optional[str] = None
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    updated_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    last_evaluated_at: Optional[datetime] = None
    next_evaluation_at: Optional[datetime] = None
    expires_at: Optional[datetime] = None

    def __post_init__(self) -> None:
        self.validate()

    def validate(self) -> None:
        """Strict validation of situation fields."""
        if not self.id or not isinstance(self.id, str) or not self.id.strip():
            raise ValueError("Situation id must be a non-empty string.")

        if not self.type or not isinstance(self.type, str) or not self.type.strip():
            raise ValueError("Situation type must be a non-empty string.")

        # Normalize status & priority
        valid_statuses = {
            SituationStatus.OPEN.value,
            SituationStatus.MONITORING.value,
            SituationStatus.RESOLVED.value,
            SituationStatus.CLOSED.value,
            SituationStatus.EXPIRED.value,
            SituationStatus.SUPPRESSED.value,
            "investigating",
        }
        if isinstance(self.status, SituationStatus):
            self.status = self.status.value
        elif isinstance(self.status, str) and self.status.strip().lower() in valid_statuses:
            self.status = self.status.strip().lower()
        else:
            raise ValueError(f"Situation status must be one of {valid_statuses}, got '{self.status}'.")

        if isinstance(self.priority, SituationPriority):
            self.priority = self.priority.value
        elif isinstance(self.priority, str):
            self.priority = self.priority.strip().lower()
        else:
            raise ValueError("Situation priority must be a string or SituationPriority enum.")

        if not isinstance(self.novelty, (int, float)):
            raise ValueError("Situation novelty must be numeric.")
        if self.novelty < 0.0 or self.novelty > 1.0:
            raise ValueError(f"Situation novelty must be between 0.0 and 1.0, got {self.novelty}.")

        if not isinstance(self.context, dict):
            raise ValueError("Situation context must be a dictionary.")

        if not isinstance(self.evidence, list):
            raise ValueError("Situation evidence must be a list.")

        if not isinstance(self.related_goals, list):
            raise ValueError("Situation related_goals must be a list.")

        self.created_at = ensure_timezone_aware(self.created_at, "created_at")
        self.updated_at = ensure_timezone_aware(self.updated_at, "updated_at")

        if self.last_evaluated_at is not None:
            self.last_evaluated_at = ensure_timezone_aware(self.last_evaluated_at, "last_evaluated_at")

        if self.next_evaluation_at is not None:
            self.next_evaluation_at = ensure_timezone_aware(self.next_evaluation_at, "next_evaluation_at")

        if self.expires_at is not None:
            self.expires_at = ensure_timezone_aware(self.expires_at, "expires_at")

    def is_active(self) -> bool:
        """Returns True if the situation is in an active tracking state (OPEN or MONITORING)."""
        return self.status in (SituationStatus.OPEN.value, SituationStatus.MONITORING.value)

    def is_expired(self, as_of: Optional[datetime] = None) -> bool:
        """Returns True if the situation has an expiration time in the past relative to as_of."""
        if self.expires_at is None:
            return False
        ref = as_of if as_of is not None else datetime.now(timezone.utc)
        ref_tz = ensure_timezone_aware(ref, "as_of")
        return self.expires_at <= ref_tz

    def is_due_for_evaluation(self, as_of: Optional[datetime] = None) -> bool:
        """Returns True if the scheduled re-evaluation time is reached."""
        if self.next_evaluation_at is None:
            return False
        ref = as_of if as_of is not None else datetime.now(timezone.utc)
        ref_tz = ensure_timezone_aware(ref, "as_of")
        return self.next_evaluation_at <= ref_tz and self.is_active()

    def schedule_evaluation(self, next_eval_dt: datetime) -> None:
        """Schedules future re-evaluation and transitions status to MONITORING if OPEN."""
        self.next_evaluation_at = ensure_timezone_aware(next_eval_dt, "next_eval_dt")
        if self.status == SituationStatus.OPEN.value:
            self.status = SituationStatus.MONITORING.value
        self.updated_at = datetime.now(timezone.utc)

    def resolve(self) -> None:
        """Marks the situation as RESOLVED and clears future scheduled evaluations."""
        self.status = SituationStatus.RESOLVED.value
        self.next_evaluation_at = None
        self.updated_at = datetime.now(timezone.utc)

    def suppress(self, suppress_until: Optional[datetime] = None) -> None:
        """Marks the situation as SUPPRESSED."""
        self.status = SituationStatus.SUPPRESSED.value
        self.next_evaluation_at = ensure_timezone_aware(suppress_until, "suppress_until") if suppress_until else None
        self.updated_at = datetime.now(timezone.utc)

    def to_dict(self) -> Dict[str, Any]:
        """Serializes situation into a dictionary."""
        ctx = dict(self.context)
        if self.information_required:
            ctx["information_required"] = True
        if self.investigation_target:
            ctx["investigation_target"] = self.investigation_target

        return {
            "id": self.id,
            "situation_id": self.id,
            "type": self.type,
            "status": self.status,
            "priority": self.priority,
            "novelty": self.novelty,
            "information_required": self.information_required,
            "investigation_target": self.investigation_target,
            "context": ctx,
            "evidence": self.evidence,
            "related_goals": self.related_goals,
            "created_at": format_iso8601(self.created_at),
            "updated_at": format_iso8601(self.updated_at),
            "last_evaluated_at": format_iso8601(self.last_evaluated_at) if self.last_evaluated_at else None,
            "next_evaluation_at": format_iso8601(self.next_evaluation_at) if self.next_evaluation_at else None,
            "expires_at": format_iso8601(self.expires_at) if self.expires_at else None,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "Situation":
        """Constructs a Situation instance from a dictionary."""
        if not isinstance(data, dict):
            raise ValueError(f"Expected dict to construct Situation, got {type(data).__name__}")

        if "type" not in data:
            raise ValueError("Missing required field 'type' in Situation data.")

        ctx = data.get("context", {})
        info_req = bool(data.get("information_required", ctx.get("information_required", False)))
        inv_target = data.get("investigation_target") or ctx.get("investigation_target")

        return cls(
            id=str(data.get("id") or data.get("situation_id") or uuid.uuid4()),
            type=data["type"],
            status=data.get("status", SituationStatus.OPEN.value),
            priority=data.get("priority", SituationPriority.MEDIUM.value),
            novelty=float(data.get("novelty", 0.0)),
            context=ctx,
            evidence=data.get("evidence", []),
            related_goals=data.get("related_goals", []),
            information_required=info_req,
            investigation_target=inv_target,
            created_at=ensure_timezone_aware(data.get("created_at", datetime.now(timezone.utc)), "created_at"),
            updated_at=ensure_timezone_aware(data.get("updated_at", datetime.now(timezone.utc)), "updated_at"),
            last_evaluated_at=ensure_timezone_aware(data["last_evaluated_at"], "last_evaluated_at") if data.get("last_evaluated_at") else None,
            next_evaluation_at=ensure_timezone_aware(data["next_evaluation_at"], "next_evaluation_at") if data.get("next_evaluation_at") else None,
            expires_at=ensure_timezone_aware(data["expires_at"], "expires_at") if data.get("expires_at") else None,
        )


@dataclass
class SituationEvaluation:
    """
    Output of a SituationEngine evaluation run.
    Contains generated candidate situations, ignored signals, and consolidated evidence references.
    """
    candidate_situations: List[Situation] = field(default_factory=list)
    ignored_signals: List[Dict[str, Any]] = field(default_factory=list)
    evidence: List[str] = field(default_factory=list)
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    evaluation_id: str = field(default_factory=lambda: str(uuid.uuid4()))

    def __post_init__(self) -> None:
        self.timestamp = ensure_timezone_aware(self.timestamp, "SituationEvaluation timestamp")

    def to_dict(self) -> Dict[str, Any]:
        """Serializes SituationEvaluation into a dictionary."""
        return {
            "evaluation_id": self.evaluation_id,
            "timestamp": format_iso8601(self.timestamp),
            "candidate_situation_count": len(self.candidate_situations),
            "candidate_situations": [s.to_dict() for s in self.candidate_situations],
            "ignored_signals": self.ignored_signals,
            "evidence": self.evidence,
        }

    def to_compact_summary(self) -> str:
        """Produces a concise text summary of the evaluation."""
        if not self.candidate_situations:
            return f"[{format_iso8601(self.timestamp)}] 0 candidate situations generated ({len(self.ignored_signals)} signals evaluated and within nominal thresholds)."

        sit_summaries = [
            f"{s.type} (priority={s.priority}, novelty={s.novelty:.2f}, evidence_count={len(s.evidence)})"
            for s in self.candidate_situations
        ]
        return f"[{format_iso8601(self.timestamp)}] Generated {len(self.candidate_situations)} candidate situations: " + "; ".join(sit_summaries)
